# Generated by Django 4.2.6 on 2023-10-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_da_tarefa', models.DateField()),
                ('hora_da_tarefa', models.TimeField()),
                ('descricao', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Em andamento'), ('C', 'Concluída')], default='P', max_length=1)),
            ],
        ),
    ]
